//----------------------------------------

// Table of content
:toc: macro
:toc-title: Sommaire
:numbered:

// Icons
:tip-caption: :bulb:
:note-caption: :paperclip:
:warning-caption: :warning:
:important-caption: :exclamation:
:caution-caption: :fire:

:baseURL: https://github.com/IUT-Blagnac/sae3-01-devapp-g2b-12

//----------------------------------------

= SAÉ 3.01 2022-2023

// Tags
image:{baseURL}/actions/workflows/codeql-python.yml/badge.svg[Quality Python]
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]

TIP: Ce dépôt présente le projet développé dans le cadre de la SAÉ 3.01 du BUT 2 Informatique de l'IUT de Blagnac.

- Version courante : {baseURL}/releases/tag/v5[v5]
- User Stories : {baseURL}/issues?q=is%3Aopen+is%3Aissue+label%3AUS[ici], reste 94 % US (17/18)
- Tâches : {baseURL}/issues?q=is%3Aopen+is%3Aissue+label%3ATâche[ici], reste 91 % (21/23)
- Backlog produit et backlog de sprint : https://github.com/orgs/IUT-Blagnac/projects/23[ici]

toc::[]

== Équipe

Projet réalisé par :

- https://github.com/PattateDouce[Rémy Guibert]
- https://github.com/Falettiattendre[Léo Faletti]
- https://github.com/ludovic-estival[Ludovic Estival]

Tuteur enseignant de l’équipe :

- mailto:teste@irit.fr[Olivier Teste]

== Hiérarchie du dépôt

- `.gitignore` => fichier des éléments à ne pas pousser (en général) sur le dépôt
- `.github` => répertoire qui contient des éléments de gestion de projet :
** `ISSUE_TEMPLATE` => repertoire qui contient quelques templates pour les issues :
*** `us.yml` => template pour les User Stories
*** `bug.yml` => template pour les issues de bug report
** `workflows` => repertoire qui contient les actions à lancer à chaque push sur le repo :
*** `codeql-python.yml` => script pour analyser l'application Python avec https://docs.github.com/fr/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql[CodeQL]
- `app` => répertoire contenant le code des applications :
** `bd` => scripts SQL de la BD
** `java` => code de l'application Java
** `php` => sources du site web
** `python` => code de l'application Python
- `docs` => répertoire contenant les documents/documentations :
** `moa` => documents de la MOA
** `bd` => documents en lien avec la base de données
** `java` => documentation utilisateur et technique de l'application Java
** `php` => documents en lien avec le site web
** `python` => documentation technique de l'application Python
- `tests` => répertoire contenant les tests :
** `php` => tests en lien avec le site web
** `python` => version de test de l'application Python
** `doc` => script de test de la procédure et du trigger


== Applications

=== IoT

Cette application donne les informations des capteurs de votre entrepôt via des graphiques.

Vous pouvez configurer plusieurs choses :

- quels capteurs doivent être pris en comptes,
- quelles données seront affichées,
- pour chaque donnée, le seuil d'alerte,
- et la fréquence à laquelle les données sont actualisées

Pour exécuter cette application il vous faut deux fichiers :

- un fichier JAR a exécuter pour afficher les informations des capteurs : {baseURL}/raw/master/app/java/main.jar[main.jar]

- un fichier Python qui recouillera les données des capteurs : {baseURL}/raw/master/app/python/main.py[main.py]

IMPORTANT: Ces deux fichier doivent impérativement se trouver dans le même répertoire

Sources de la version 5 :

- Java : {baseURL}/tree/master/app/java/src/[ici]
- Python : {baseURL}/tree/master/app/python/[ici]

=== Site web

Lien du site web :

- http://192.168.224.139/~SAESYS12/[Réseau filaire de l'IUT] 
- http://193.54.227.164/~SAESYS12/[Autre réseau]

Sources de la version 5 : {baseURL}/tree/master/app/php/[ici]

=== Base de données

- Le script de création de la base de données se trouve {baseURL}/raw/master/app/bd/Script%20de%20cr%C3%A9ation%20de%20la%20base.sql[ici].

- Le script d'insertion dans la base de données se trouve {baseURL}/raw/master/app/bd/Script%20d%27insertion%20dans%20la%20base.sql[ici].

- Script de la procédure {baseURL}/raw/master/app/bd/Script%20de%20la%20procédure%20Commander.sql[ici]

- Script du trigger {baseURL}/raw/master/app/bd/Script%20du%20trigger%20t_i_quantite.sql[ici].

== Documentations

=== IoT

- Documentation technique du programme Python {baseURL}/blob/master/docs/python/python_tech.adoc[ici]

WARNING: LES DOCUMENTATIONS JAVA NE SONT PAS ENCORE ÉCRITES, ELLES SONT MARQUÉES ICI À TITRE INDICATIF

- Documentation utilisateur de l'application Java {baseURL}/blob/master/docs/java/java_user.adoc[ici] (pas encore fait)

- Documentation technique de l'application Java {baseURL}/blob/master/docs/java/java_tech.adoc[ici] (pas encore fait)

=== Site web

- Charte graphique : {baseURL}/raw/master/docs/php/Charte%20graphique.pdf[ici]

- Schéma d'enchaînement des pages : {baseURL}/raw/master/docs/php/Schéma%20d%27Enchaînement%20des%20Pages.pdf[ici]

- Code commenté de l'authentification : {baseURL}/raw/master/docs/php/Authentification.pdf[ici]

- Code commenté consultation produits et modification compte : {baseURL}/raw/master/docs/php/Affichage%20produits%20et%20modification%20compte.pdf[ici]

=== Base de données

- Le diagramme de classes, le dictionnaire de données et le schéma relationnel sont regroupé dans {baseURL}/raw/master/docs/bd/Conception%20de%20la%20base%20de%20donn%C3%A9es.pdf[la conception de la base de données]

- Le document de création et d'insertion se trouve {baseURL}/raw/master/docs/bd/Cr%C3%A9ation%20et%20insertion%20de%20la%20base.pdf[ici].

- Le document concernant le trigger et la procédure se trouve {baseURL}/raw/master/docs/bd/Trigger%20et%20procédure.pdf[ici].

=== Évaluations hebdomadaires

NOTE: Les notes ci-dessous sont mises à jour directement par les enseignants responsables de la compétence 5.

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=935875429&format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=935875429&format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=935875429&format=image"></iframe>
++++
endif::[]

==== Retour Sprint 3

Liens à jour dans le readme.

Dans le Backlog revoir les US, il manque les priorités et la rédaction de la US.

Différencier IOT et site WEB.

Identifier les sprints.

Identifier à quelle US se rattache une tâche.

Release Ecommerce ?

Rien sur les tests.

==== Retour Sprint 4

Documentations : J'ai un squelette vide, à compléter et versionner !

Tests : ok

Livrables : lien vers le site c'est bien, pensez à mettre un lien vers les codes sources versionnés. Je n'ai pas le lien pour IOT.

Attention à partir de maintenant on ne fouille plus dans vos dépôts ! Il me manque donc les liens vers : les backlogs produits, les backlogs de sprint !!

La numérotation des sprints suit ce que vous a dit M. Bruel on vient de terminer le sprint 4, on prévois le sprint 5. Pensez à garder une trace des sprints terminés dans Github !

== Tests

=== IoT

Pour la partie Python les tests sont implémentés dans un autre script, se trouvant {baseURL}/raw/master/tests/python/main-test.py[ici], les tests sont expliqués dans la documentation technique, {baseURL}/blob/master/docs/python/python_tech.adoc#tests[ici].

=== PHP

Vous pouvez retrouver les tests du site web {baseURL}/blob/master/tests/php/tests-php.adoc[ici].

=== Base de données

Des scripts de test pour le trigger et la procédure sont disponible {baseURL}/raw/master/tests/bd/Procédure%20Commander.sql[ici] et {baseURL}/raw/master/tests/bd/Trigger%20t_i_quantite.sql[ici]
