//----------------------------------------

// Table of content
:toc: macro
:toc-title: Sommaire
:numbered:

// Icons
:tip-caption: :bulb:
:note-caption: :paperclip:
:warning-caption: :warning:
:important-caption: :exclamation:
:caution-caption: :fire:

:baseURL: https://github.com/IUT-Blagnac/sae3-01-devapp-g2b-12

//----------------------------------------

= SAÉ 3.01 2022-2023

// Tags
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build]
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests]
image:{baseURL}/actions/workflows/quality.yml/badge.svg[Quality]
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]

TIP: Ce dépôt présente le projet développé dans le cadre de la SAÉ 3.01 du BUT 2 Informatique de l'IUT de Blagnac.

- Version courante : {baseURL}/releases/tag/v1[v1]
- Lien vers les User Stories et Issues https://github.com/orgs/IUT-Blagnac/projects/23[ici], reste 100 % US

toc::[]

== Équipe

Projet réalisé par :

- https://github.com/PattateDouce[Rémy Guibert]
- https://github.com/Falettiattendre[Léo Faletti]
- https://github.com/ludovic-estival[Ludovic Estival]


== Hiérarchie du dépôt

- `.gitignore` => fichier des éléments à ne pas pousser (en général) sur le dépôt
- `.github` => répertoire qui contient des éléments de gestion de projet :
** `ISSUE_TEMPLATE` => repertoire qui contient quelques templates pour les issues :
*** `us.yml` => template pour les User Stories
*** `bug.yml` => template pour les issues de bug report
** `workflows` => repertoire qui contient les actions à lancer à chaque push sur le repo :
*** `build.yml` => script pour build l'application
*** `tests.yml` => script pour tester l'application
- `app` => répertoire contenant le code des applications :
** `java` => code de l'application Java
** `php` => code du site web
** `python` => code de l'application Python
- `docs` => répertoire contenant les documentations :
** `moa` => documents de la MOA
** `bd` => documents en lien avec la base de données
** `java` => documentation utilisateur et technique de l'application Java
** `php` => documents en lien avec le site web
** `python` => documentation technique de l'application Python


== Applications 

=== IOT

Cette application donne les informations des capteurs de votre entrepôt via des graphiques.

Vous pouvez configurer plusieurs choses :

- quels capteurs doivent être pris en comptes,
- quelles données seront affichées,
- pour chaque donnée, le seuil d'alerte,
- et la fréquence à laquelle les données sont actualisées

Pour exécuter cette application il vous faut deux fichiers :

- un fichier JAR a exécuter pour afficher les informations des capteurs : {baseURL}/raw/master/app/java/main.jar[main.jar]

- un fichier Python qui recouillera les données des capteurs : {baseURL}/raw/master/app/python/main.py[main.py]

IMPORTANT: Ces deux fichier doivent impérativement se trouver dans le même répertoire

=== Site web

Le dossier racine du site web se trouve dans le réportoire `{baseURL}/tree/master/app/php/[app/php]`

Tous les fichiers et répertoires du dossier racine doivent être téléversés sur le serveur qui hébergera votre site web.

== Documentations

=== IOT

- Documentation utilisateur de l'application Java {baseURL}/blob/master/docs/java/java_user.adoc[ici]

- Documentation technique de l'application Java {baseURL}/blob/master/docs/java/java_tech.adoc[ici]

- Documentation technique du programme Python {baseURL}/blob/master/docs/python/python_tech.adoc[ici]
