DROP TABLE QUANTITE;

DROP TABLE COMMANDE;

DROP TABLE PAYPAL;

DROP TABLE CARTEBANCAIRE;

DROP TABLE REGLEMENT;

DROP TABLE PANIER;

DROP TABLE PRODUIT;

DROP TABLE CATEGORIE;

DROP TABLE CLIENT;


CREATE TABLE CLIENT
(
	IDCLIENT NUMBER(10) NOT NULL,
	NOM VARCHAR2(128) NOT NULL,
	PRENOM VARCHAR2(128) NOT NULL,
	MAIL VARCHAR2(128) NOT NULL,
	MDP VARCHAR2(128) NOT NULL,
	AGRICULTEUR NUMBER(1),
	CONSTRAINT PK_CLIENT PRIMARY KEY (IDCLIENT)
);


CREATE TABLE CATEGORIE
(
	IDCATEGORIE NUMBER(10) NOT NULL,
	IDCATEGORIEPARENT NUMBER(10) NOT NULL,
	NOM VARCHAR2(128) NOT NULL,
	CONSTRAINT PK_CATEGORIE PRIMARY KEY (IDCATEGORIE),
    CONSTRAINT FK_CATEGORIE_CATEGORIE FOREIGN KEY (IDCATEGORIEPARENT) REFERENCES CATEGORIE (IDCATEGORIE)
);


CREATE TABLE PRODUIT
(
	IDPRODUIT NUMBER(10) NOT NULL,
	IDCATEGORIE NUMBER(10) NOT NULL,
	NOM VARCHAR2(128) NOT NULL,
	DESCRIPTION VARCHAR2(2048),
	POIDS NUMBER(5,2) NOT NULL,
	PRIX NUMBER(10,2) NOT NULL,
	STOCK NUMBER(10) NOT NULL,
	CONSTRAINT PK_PRODUIT PRIMARY KEY (IDPRODUIT),
	CONSTRAINT FK_PRODUIT_CATEGORIE FOREIGN KEY (IDCATEGORIE) REFERENCES CATEGORIE (IDCATEGORIE)
);


CREATE TABLE PANIER
(
	IDCLIENT NUMBER(10) NOT NULL,
	IDPRODUIT NUMBER(10) NOT NULL,
	QUANTITE NUMBER(10) NOT NULL,
	CONSTRAINT PK_PANIER PRIMARY KEY (IDCLIENT, IDPRODUIT),
	CONSTRAINT FK_PANIER_PRODUIT FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT (IDPRODUIT),
	CONSTRAINT FK_PANIER_CLIENT FOREIGN KEY (IDCLIENT) REFERENCES CLIENT (IDCLIENT)
);


CREATE TABLE REGLEMENT
(
	IDREGLEMENT NUMBER(10) NOT NULL,
	CONSTRAINT PK_REGLEMENT PRIMARY KEY (IDREGLEMENT)
);


CREATE TABLE CARTEBANCAIRE
(
	IDREGLEMENT NUMBER(10) NOT NULL,
	NUMCB NUMBER(16) NOT NULL,
	CRYPTOGRAMME NUMBER(3) NOT NULL,
	MOISEXPIRATION NUMBER(2) NOT NULL,
	ANNEEEXPIRATION NUMBER(4) NOT NULL,
	CONSTRAINT PK_CARTEBANCAIRE PRIMARY KEY (IDREGLEMENT),
	CONSTRAINT FK_CARTEBANCAIRE_REGLEMENT FOREIGN KEY (IDREGLEMENT) REFERENCES REGLEMENT (IDREGLEMENT)
);


CREATE TABLE PAYPAL
(
	IDREGLEMENT NUMBER(10) NOT NULL,
	CONSTRAINT PK_PAYPAL PRIMARY KEY (IDREGLEMENT),
	CONSTRAINT FK_PAYPAL_REGLEMENT FOREIGN KEY (IDREGLEMENT) REFERENCES REGLEMENT (IDREGLEMENT)
);


CREATE TABLE COMMANDE
(
	IDCOMMANDE NUMBER(10) NOT NULL,
	IDCLIENT NUMBER(10) NOT NULL,
	IDREGLEMENT NUMBER(10) NOT NULL,
	ADRESSE VARCHAR2(128) NOT NULL,
	VILLE VARCHAR2(128) NOT NULL,
	CODEPOSTAL NUMBER(6) NOT NULL,
	CONSTRAINT PK_COMMANDE PRIMARY KEY (IDCOMMANDE),
	CONSTRAINT FK_COMMANDE_CLIENT FOREIGN KEY (IDCLIENT) REFERENCES CLIENT (IDCLIENT),
	CONSTRAINT FK_COMMANDE_REGLEMENT FOREIGN KEY (IDREGLEMENT) REFERENCES REGLEMENT (IDREGLEMENT)
);


CREATE TABLE QUANTITE
(
	IDPRODUIT NUMBER(10) NOT NULL,
	IDCOMMANDE NUMBER(10) NOT NULL,
	QUANTITE NUMBER(10) NOT NULL,
	PRIXUNITAIRE NUMBER(10,2) NOT NULL,
	CONSTRAINT PK_QUANTITE PRIMARY KEY (IDPRODUIT, IDCOMMANDE),
	CONSTRAINT FK_QUANTITE_PRODUIT FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT (IDPRODUIT),
	CONSTRAINT FK_QUANTITE_COMMANDE FOREIGN KEY (IDCOMMANDE) REFERENCES COMMANDE (IDCOMMANDE)
);
