//----------------------------------------

// Table of content
:toc: macro
:toc-title: Sommaire
:numbered:

// Icons
:tip-caption: :bulb:
:note-caption: :paperclip:
:warning-caption: :warning:
:important-caption: :exclamation:
:caution-caption: :fire:

:baseURL: https://github.com/IUT-Blagnac/sae3-01-devapp-g2b-12

//----------------------------------------

= Documentation technique de l'application Python

toc::[]

== Equipe

Documentation rédigée par :

* Rémy GUIBERT

== Utilisation

Ce programme sert à enregistrer des informations récupérées de capteurs d'un réseau MQTT.

On peut paramétrer de quels capteurs on récupère les données, quelles données sont enregistrées, à quelle fréquence et quel est la valeur maximale pour chaque données.

Pour configurer le programme référez-vous à la section https://github.com/IUT-Blagnac/sae3-01-devapp-g2b-12/blob/master/docs/python/python_tech.adoc#configuration[Configuration].

Les informations récupérées sont enregistrées dans le fichier `data.json`.

Pour utiliser ce programme assurez-vous qu'un fichier de configuration bien formaté se trouve dans le même répertoire puis il suffit simplement de l'exécuter.

=== Erreurs

Le programme est fait pour ne pas fonctionner dans le cas où le fichier de configuration n'est pas correctement formaté.

Il affichera dans la console le message suivant : `Le fichier de configuration ("config.json") est manquant ou mal écrit.`

Le fichier de configuration n'est pas analysé en profondeur donc il peut y avoir des bugs par rapport à une trés mauvaise configuration.

À part ça il ne devrait pas y avoir d'erreurs lié au programme.

=== Nominale

À la connexion au serveur MQTT le programma affiche un message.

Le programme affichera aussi un message au cas où une donnée dépasse sa valeur maximale, indiquant quelle donnée à dépassée son seuil et de combien.

Les données reçues des capteurs sont enregistrées dans le fichier `data.json` dans un object JSON sous la forme `"<nom_donnée>" : <valeur_donnée>`, où `<nom_donnée>` est le nom technique de la donnée (voir section https://github.com/IUT-Blagnac/sae3-01-devapp-g2b-12/blob/master/docs/python/python_tech.adoc#données[Donnée(s)]) et `<valeur_donnée>` est la valeur envoyés d'un capteur pouvant être un nombre entier ou décimal.

== Configuration

Le programme est configurable via le fichier `config.json`.

Ce fichier permet de paramétrer 6 options correspondant à 6 couples clé-valeur dans l'objet JSON :

|===
| Clé | Valeur | Type Valeur | Configurable via l'application Java

| `devices` | Quels capteurs doivent être pris en comptes | Liste de chaînes | Oui
| `data_wanted` | Quelles données seront enregistrées | Liste de chaînes | Oui
| `alert_values` | Pour chaque donnée, son seuil d'alerte | Liste de nombres | Oui
| `frequency`| Fréquence à laquelle les données sont enregistrées | Entier | Oui
| `host`| Nom de domaine du serveur MQTT | Chaîne | Non
| `port`| Port du serveur MQTT | Entier | Non
|===

=== Appareil(s)

Pour paramétrer de quel(s) appareil(s) on récupère les informations il faut changer la valeur de `devices`.

Cette valeur doit être une liste d'une ou plusieurs chaînes.

Les chaînes correspondent à l'adresse MAC d'un capteur.

Pour prendre en compte les données de tous les capteurs il suffit de mette `"#"` dans cette liste.

=== Donnée(s)

Le programme est capable d'extraire 9 données des capteurs :

|===
| Nom | Valeur | Unité

| `activity` | Activité dans un rayon de 5 mètre autour du capteur | Pas d'unité (valeur de 0 à 65535)
| `co2` | Concentration en CO2 | ppm
| `humidity` | Taux d'humidité | RH
| `illumination` | Éclairage | lux
| `infrared`| Infrarouge | lux
| `infrared_and_visible`| Infrarouge et lumière visible | lux
| `pressure`| Pression atmosphérique | hPa
| `temperature`| Température ambiante | °C
| `tvoc`| Composants organiques volatils | ppb
|===

Pour paramétrer quelles données sont prisent en compte il faut changer la valeur de `data_wanted`.

Cette valeur doit être une liste d'une ou plusieurs chaînes.

Les chaînes correspondent au nom d'une donnée dans le tableau ci-dessus.

=== Valeur(s) max

Chaque valeur ajoutée dans `data_wanted` doit avoir une valeur max.

La valeur max peut être un nombre entier ou décimal.

La première valeur de la liste `alert_values` correspond à la valeur max pour la première donnée de `data_wanted`, la deuxième valeur à la deuxième donnée, etc.

=== Fréquence

Pour paramétrer à quelle fréquence les données sont enregistrées il faut changer la valeur de `frequency`.

Cette valeur doit être un entier.

Cela correspond au nombre de minute entre chaque enregistrement.

Si la valeur est mise à `0` il n'y aura pas de délai avant chaque enregistrement.

=== Hôte

Le nom de domaine du serveur MQTT peut être paramétré en changeant la valeur de `host`.

Par défaut il est paramétré sur `chirpstack.iut-blagnac.fr`.

=== Port

Le port du serveur MQTT peut être paramétré en changeant la valeur de `port`.

Le port par défaut est `1883`.
